QT += sql
######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 23 18:33:38 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += laptopdata.h mainwindow.h return.h take.h
FORMS += mainwindow.ui return.ui take.ui
SOURCES += laptopdata.cpp main.cpp mainwindow.cpp return.cpp take.cpp

DISTFILES +=
